'use client';

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { ArrowLeft, FileText } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-950 via-gray-900 to-black text-white">
      <header className="border-b border-white/10 bg-white/5 backdrop-blur-xl">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <Link href="/">
            <Button variant="ghost" className="text-white/70 hover:text-white">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to App
            </Button>
          </Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-12">
        <div className="flex items-center gap-3 mb-8">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center">
            <FileText className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-bold">Terms of Service</h1>
            <p className="text-white/50">Last updated: January 2025</p>
          </div>
        </div>

        <Card className="bg-white/5 border-white/10 backdrop-blur-xl">
          <div className="p-8 space-y-8">
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
              <p className="text-white/70 leading-relaxed">
                By accessing and using Thumbnail Generator ("Service"), you accept and agree to be bound by the terms 
                and provisions of this agreement. If you do not agree to abide by these terms, please do not use this service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">2. Description of Service</h2>
              <p className="text-white/70 leading-relaxed">
                Thumbnail Generator is an AI-powered tool that allows users to create YouTube thumbnails. 
                The service provides various styles, backgrounds, and customization options for thumbnail generation.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">3. User Responsibilities</h2>
              <div className="text-white/70 leading-relaxed">
                <p>Users agree to:</p>
                <ul className="list-disc list-inside space-y-2 ml-4 mt-4">
                  <li>Use the service only for lawful purposes</li>
                  <li>Not generate content that infringes on intellectual property rights</li>
                  <li>Not create harmful, offensive, or illegal content</li>
                  <li>Not attempt to overload or abuse the service</li>
                  <li>Comply with all applicable laws and regulations</li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">4. Intellectual Property</h2>
              <p className="text-white/70 leading-relaxed">
                The thumbnails generated by our service are provided for personal and commercial use. However, 
                we do not guarantee that generated content will not infringe on third-party rights. Users are 
                responsible for ensuring their use of generated content complies with applicable laws.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">5. Limitation of Liability</h2>
              <p className="text-white/70 leading-relaxed">
                The service is provided "as is" without warranties of any kind. We are not liable for any 
                damages arising from the use of our service, including but not limited to direct, indirect, 
                incidental, or consequential damages.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">6. Service Modifications</h2>
              <p className="text-white/70 leading-relaxed">
                We reserve the right to modify, suspend, or discontinue any part of the service at any time 
                without prior notice. We may also update these terms periodically.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">7. Contact</h2>
              <p className="text-white/70 leading-relaxed">
                For questions about these Terms of Service, contact us at: 
                <span className="text-purple-400"> legal@thumbnailgenerator.ai</span>
              </p>
            </section>
          </div>
        </Card>

        <div className="flex gap-4 mt-8">
          <Link href="/privacy">
            <Button variant="outline" className="border-white/20 text-white hover:bg-white/10">
              Privacy Policy
            </Button>
          </Link>
          <Link href="/cookies">
            <Button variant="outline" className="border-white/20 text-white hover:bg-white/10">
              Cookie Policy
            </Button>
          </Link>
        </div>
      </main>
    </div>
  );
}
